/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.lyzrd.sparky;

import static spark.Spark.*;

public class App {
    public static String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        get("/hello", (req, res) -> getGreeting());
        System.out.println(getGreeting());
    }
}
